//! Build script: turns the vendored Factory Zero registry entry into a Rust
//! table.
//!
//! `data/stack.json` is a verbatim copy of Sealbin's entry in the Factory Zero
//! registry (<https://factory0.ventures/stack.json>); `data/PROVENANCE.md`
//! records where it came from and when. The copy is compiled in, so neither the
//! CLI nor the shipped binary ever makes a network call, and `serde_json` is a
//! build-dependency only — the shipped binary gains no dependency at all.
//!
//! `crates/sealb/tests/built_with.rs` re-reads the same file and compares it to
//! the registry over the network in a `#[ignore]`d test, so a drift between this
//! copy and the published registry fails CI.

use std::fmt::Write as _;
use std::{env, fs, path::PathBuf};

/// The registry document this crate's copy is one entry of.
const REGISTRY_URL: &str = "https://factory0.ventures/stack.json";

/// Statuses the registry may publish. Anything else is a build error: the
/// rendering and the tests both promise that the word `live` means exactly
/// "in use today", so a new status must be looked at rather than rendered.
const STATUSES: &[&str] = &["live", "planned"];

fn main() {
    println!("cargo:rerun-if-changed=data/stack.json");
    println!("cargo:rerun-if-changed=build.rs");

    let data = fs::read_to_string("data/stack.json")
        .expect("sealb: data/stack.json is missing; see data/PROVENANCE.md");
    let entry: serde_json::Value =
        serde_json::from_str(&data).expect("sealb: data/stack.json is not valid JSON");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("sealb: cargo did not set OUT_DIR"));
    fs::write(out_dir.join("built_with.rs"), generate(&entry))
        .expect("sealb: could not write the generated built_with.rs");
}

/// Renders the whole generated module, including its `//!` header and the
/// `Entry` table `built_with.rs` includes it into.
fn generate(entry: &serde_json::Value) -> String {
    let page = str(entry, "page");
    let uses = entry
        .get("uses")
        .and_then(serde_json::Value::as_array)
        .filter(|uses| !uses.is_empty())
        .unwrap_or_else(|| panic!("sealb: data/stack.json has an empty or missing `uses`"));

    let mut out = String::new();
    out.push_str(
        "// @generated by crates/sealb/build.rs from data/stack.json. Do not edit.\n\
         //\n\
         // The bytes come from the vendored Factory Zero registry entry; see\n\
         // data/PROVENANCE.md for the URL, the retrieval date and the rule that\n\
         // the registry changes first.\n\n",
    );
    let _ = writeln!(out, "/// The registry page listing this venture's uses.");
    let _ = writeln!(out, "pub const PAGE: &str = {page:?};");
    let _ = writeln!(
        out,
        "/// The registry document the vendored copy came from."
    );
    let _ = writeln!(out, "pub const SOURCE: &str = {REGISTRY_URL:?};");
    out.push_str(
        "\n/// Every use, in registry order. Order is data, not presentation:\n\
                    /// the registry decides it and the render must not reshuffle it.\n\
                    pub const ENTRIES: &[Entry] = &[\n",
    );

    for use_ in uses {
        let status = str(use_, "status");
        assert!(
            STATUSES.contains(&status.as_str()),
            "sealb: data/stack.json has status `{status}`, which the registry does not publish; \
             only live and planned exist (data/PROVENANCE.md)"
        );
        let _ = writeln!(out, "    Entry {{");
        for field in [
            "id", "name", "url", "role", "phrase", "status", "note", "kind",
        ] {
            let _ = writeln!(out, "        {field}: {:?},", str(use_, field));
        }
        let _ = writeln!(out, "    }},");
    }
    out.push_str("];\n");
    out
}

/// Reads one required string field, failing the build with a useful message.
fn str(value: &serde_json::Value, field: &str) -> String {
    value
        .get(field)
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| panic!("sealb: data/stack.json is missing the string field `{field}`"))
        .to_owned()
}
